user:
api-key:
tunnel-identifier: <tunnelName>
verbose: 0
region: <sauceRegion>
logfile: "-"
no-ssl-bump-domains: [ all ]
shared-tunnel: false
proxy-tunnel: false
no-autodetect: true
no-remove-colliding-tunnels: false
ocsp: log-only